### ISSUE TITLE
broken links to PDFs

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/v4#4]
Got an email from someone about broken links to slides/pdfs from this page:

https://v4.software-carpentry.org/python/funcobj.html

Link to  
https://v4.software-carpentry.org/v4/python/funcobj.pdf
should be
https://v4.software-carpentry.org/python/funcobj.pdf

Same for links in all the other parts of the lesson.  
Links in front matter on each page need to be updated.

**Comment by voanna** [comment]
Any progress on this? I love the older lessons, and I was really worried they were gone forever, until I found this issue.

**Comment by gvwilson** [comment]
Should now be corrected (apologies for the delay) - please check and let us know?

**Comment by voanna** [comment]
The links to the materials  (Version Control/Introduction at YouTube/slides /PDF) are still broken on  this page https://v4.software-carpentry.org/vc/intro.html, for example and seem to be broken on other lesson pages too.

**Comment by gvwilson** [comment]
I don't understand - I'll dig further.

**Comment by voanna** [comment]
You don't understand my comment or why it's not working? Also, a correction: the youtube link does still work but the slides and pdf links don't

**Comment by gvwilson** [comment]
I understand the comment - everything works when I build locally, but 
there's an extra path element when the pages are automatically built on 
GitHub, and I don't yet know where it's coming from.

**Comment by gvwilson** [comment]
This should now be corrected - please have a look and let us know.

**Comment by voanna** [comment]
Well now Chrome won't let me navigate to that page and I get this error:

Your connection is not private

Attackers might be trying to steal your information from v4.software-carpentry.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

In fact I think the certificate for the entire v4.software-carpentry.org subdomain is invalid.

**Comment by gvwilson** [comment]
OK, I followed this path to get to the PDF:
- http://v4.software-carpentry.org/
- http://v4.software-carpentry.org/shell/index.html
- http://v4.software-carpentry.org/shell/filedir.html
- http://v4.software-carpentry.org/shell/filedir.pdf

So it looks like the problem is the cert, and I'll chase that down. Glad you're able to get through to the PDFs now - thanks for your patience.

**Comment by voanna** [comment]
Works!

**Comment by voanna** [comment]
Thank you :)

**Comment by pipitone** [comment]
Just a heads up that the HTTPS problems you're seeing are because of a recent switch we made to hosting v4.software-carpentry.org on github pages... and that platform doesn't support HTTPS on a custom domain[1].

[1] https://github.com/isaacs/github/issues/156
